/* ── DOM Helpers ──────────────────────────────────────────────────────── */

const $ = (sel, ctx) => (ctx || document).querySelector(sel)
const $$ = (sel, ctx) => Array.from((ctx || document).querySelectorAll(sel))

const on = (el, ev, fn, opts) => {
  if (!el) return
  ;(typeof el === 'string' ? $$(el) : [el]).forEach(e => e.addEventListener(ev, fn, opts))
}
const delegate = (parent, sel, ev, fn) => {
  if (typeof parent === 'string') parent = $(parent)
  if (!parent) return
  parent.addEventListener(ev, e => {
    const t = e.target && typeof e.target.closest === 'function' ? e.target.closest(sel) : null
    if (t && parent.contains(t)) fn(e, t)
  })
}

/* ── LocalStorage Helpers ─────────────────────────────────────────────── */

const store = {
  get(key, def) {
    try { const v = localStorage.getItem('oou_' + key); return v ? JSON.parse(v) : def }
    catch { return def }
  },
  set(key, val) {
    try { localStorage.setItem('oou_' + key, JSON.stringify(val)) } catch {}
  },
  remove(key) {
    try { localStorage.removeItem('oou_' + key) } catch {}
  }
}

/* ── Debounce / Throttle ──────────────────────────────────────────────── */

const debounce = (fn, ms) => { let t; return (...a) => { clearTimeout(t); t = setTimeout(() => fn(...a), ms) } }
const throttle = (fn, ms) => { let wait; return (...a) => { if (!wait) { fn(...a); wait = true; setTimeout(() => { wait = false }, ms) } } }

/* ── Spring Physics Engine ────────────────────────────────────────────── */

function createSpring({ stiffness = 450, damping = 45, mass = 0.5, from = 0 } = {}) {
  let value = from
  let velocity = 0
  let target = from
  let rafId = null
  let prevTime = null
  const listeners = []

  function tick(time) {
    const dt = prevTime === null ? 1/60 : Math.min((time - prevTime) / 1000, 1/30)
    prevTime = time

    const spring = -stiffness * (value - target)
    const damper = -damping * velocity
    const accel = (spring + damper) / mass
    velocity += accel * dt
    value += velocity * dt

    if (!isFinite(value)) { value = target; velocity = 0; prevTime = null; rafId = null; return }

    listeners.forEach(fn => fn(value))

    if (Math.abs(velocity) > 0.001 || Math.abs(value - target) > 0.001) {
      rafId = requestAnimationFrame(tick)
    } else {
      value = target
      velocity = 0
      rafId = null
      prevTime = null
    }
  }

  return {
    setTarget(t) {
      target = t
      if (!rafId) {
        prevTime = null
        rafId = requestAnimationFrame(tick)
      }
    },
    getValue() { return value },
    onChange(fn) { listeners.push(fn); return () => { const i = listeners.indexOf(fn); if (i > -1) listeners.splice(i, 1) } },
    destroy() { if (rafId) { cancelAnimationFrame(rafId); rafId = null; prevTime = null } }
  }
}

/* ── Price Formatting ─────────────────────────────────────────────────── */

function formatPrice(amount) {
  const num = Number(amount)
  return '\u20B9' + (isNaN(num) ? '0' : num.toLocaleString('en-IN'))
}

/* ── Clamp ─────────────────────────────────────────────────────────────── */

function clamp(val, min, max) { return Math.min(Math.max(val, min), max) }

/* ── Coupon Codes ────────────────────────────────────────────────────────── */

const COUPONS = {
  YARNLOVE: { discount: 15, label: 'Yarn Lover', type: 'percent', minAmount: 0 },
  OOU: { discount: 15, label: 'Oouni Fan', type: 'percent', minAmount: 0 }
}

const REVIEW_TEMPLATES = {
  default: { author: 'Aaradhya Joshi', avatar: '🌸', comment: 'Absolutely obsessed with my product! The stitches are so neat, and the texture is incredibly cozy. You can really feel the hours of love knitted into it.' }
}

function makeReviews(productName, category, rating) {
  return [
    { id: 'rev-1', author: 'Aaradhya Joshi', rating: 5, comment: `Absolutely obsessed with my ${productName}! The stitches are so neat, and the texture is incredibly cozy. You can really feel the hours of love knitted into it.`, date: '2026-05-14', avatar: '🌸' },
    { id: 'rev-2', author: 'Suhana Gupta', rating: 5, comment: 'Exactly as pictured on Pinterest! It goes perfectly with my room setup. Delivery was fast, and the packaging smelled of beautiful dried lavender flowers.', date: '2026-06-20', avatar: '🌷' }
  ]
}

/* ── Gallery Items ──────────────────────────────────────────────────────── */

const galleryItems = [
  { id: 'g-1', image: 'assets/images/crochet_bags_hero_1783006461148.jpg', title: 'Warm Sunday Styling', description: 'A vintage cream flower bag catching the autumn leaves.', likes: 142 },
  { id: 'g-2', image: 'assets/images/crochet_plushies_1783006474452.jpg', title: 'The Shelf Guardians', description: 'Our Matcha Froggy making friends on a dreamy bookshelf.', likes: 298 },
  { id: 'g-3', image: 'assets/images/crochet_flowers_1783006487670.jpg', title: 'Forever Bouquet Studio Session', description: 'Lavender arrangement resting in warm, sunlit cotton linen.', likes: 184 },
  { id: 'g-4', image: 'assets/images/crochet_coasters_1783006500338.jpg', title: 'Slow Mornings & Chai', description: 'The mocha coaster set grounding a fresh cup of organic masala chai.', likes: 211 },
  { id: 'g-5', image: 'assets/images/crochet_wearables_1783006542606.jpg', title: 'Draped in Craftsmanship', description: 'Showing off the dense floral motif stitches of our Autumn Cardigan.', likes: 405 },
  { id: 'g-6', image: 'assets/images/crochet_home_decor_1783006530187.jpg', title: 'Peaceful Wall Accents', description: 'Boho Wall Hanging adding soft geometric vibes to a cozy nursery room.', likes: 195 }
]

/* ── FAQ Data ───────────────────────────────────────────────────────────── */

const faqs = [
  { question: 'How long does a custom order typically take?', answer: 'Because every item is handcrafted stitch by stitch with zero industrial machinery, custom plushies or accessories take 5 to 10 business days to knit and finish. Complex wearables, like custom sweaters, can take up to 2 to 3 weeks. Once completed, your order is packaged beautifully with natural botanicals and shipped with full tracking.' },
  { question: 'What materials do you use? Is it baby-safe?', answer: 'Yes, absolutely! We prioritize high-grade natural and hypoallergenic materials. Our plushies use premium hypoallergenic velvet polyester fiberfill and cotton chenille yarn. Our wear and home accessories are crafted from 100% organic Indian cotton, fine wool, or soft milk cotton blends. All safety eyes are screw-backed, although we recommend supervising children under 3 years with keychains.' },
  { question: 'How do I care for my crochet items?', answer: 'Crochet requires gentle care. For bags and coasters, hand wash with lukewarm water and mild soap, then lay flat on a dry towel in a shaded area. Never wring or twist crochet, as this distorts the shape. For wearables like cardigans, lay flat on a flat drying rack; hanging them will cause the gravity to pull and stretch the yarn fibers over time.' },
  { question: 'Can I send you a Pinterest design for custom orders?', answer: 'Absolutely! That is what our Custom Order portal is designed for. You can fill out our interactive form, upload your Pinterest inspiration screenshots, choose your dream yarn color palette, and provide rough dimensions. We will review your request and send a detailed sketch and WhatsApp quote within 24 hours!' },
  { question: 'Do you ship across India and globally?', answer: 'Yes! We ship our cozy creations all over India (including Delhi, Mumbai, Bangalore, Pune, etc.) and worldwide from our studio in Haldwani, Uttarakhand. Delivery times range from 3-5 days for domestic orders and 10-15 days for international destinations. We secure every order with beautiful, eco-friendly custom boxes packed with dried lavender pods and care reminder tags.' }
]

/* ── Product Data (matching React source exactly) ───────────────────────── */

const products = {
  'p-1': { id: 'p-1', name: 'Muguet Floral Crochet Shoulder Bag', tagline: 'Hand-knitted vintage bag with delicate daisy embellishments.', price: 1850, rating: 4.9, category: 'bags', image: 'assets/images/crochet_bags_hero_1783006461148.jpg', secondaryImages: ['assets/images/crochet_bags_hero_1783006461148.jpg', 'assets/images/crochet_accessories_1783006515912.jpg'], description: 'Our signature shoulder bag is handcrafted over 14 hours of continuous fine knitting by master artisans. Made with premium, organic Indian cotton yarn, it features detailed floral appliques stitched row by row. Perfect for carrying your notebook, wallet, and favorite lip balms.', story: 'Designed during a quiet, misty morning in our Landour studio, this bag draws inspiration from vintage hill-station cottagecore aesthetics. Every single daisy is knitted separately using a micro-hook and securely anchored into the dense, double-walled mesh body to ensure lifelong durability without stretching.', materials: ['100% Organic Coimbatore Cotton Yarn', 'Satin Inner Lining', 'Magnetic Brass Clasp'], careInstructions: ['Hand wash gently in lukewarm water with mild liquid detergent.', 'Do not wring; press water out gently between towels.', 'Lay flat on a clean dry towel to dry away from direct sunlight.'], stockStatus: 'In Stock', isBestSeller: true, isFeatured: true, reviews: makeReviews('Muguet Floral Bag', 'bags', 4.9), size: '12" x 10" with a 14" strap drop', colorVariants: [{ name: 'Cream Blossom', hex: '#FFFBF7' }, { name: 'Peach Sorbet', hex: '#F7D8DE' }, { name: 'Sage Meadow', hex: '#A9C1A5' }] },
  'p-2': { id: 'p-2', name: 'Matcha Froggy & Cozy Mushroom Plushie Duo', tagline: 'Lovable companions that keep your bookshelf cozy.', price: 899, rating: 5.0, category: 'plushies', image: 'assets/images/crochet_plushies_1783006474452.jpg', secondaryImages: ['assets/images/crochet_plushies_1783006474452.jpg', 'assets/images/crochet_home_decor_1783006530187.jpg'], description: 'A charming duo featuring a smiling matcha-colored forest frog wearing a micro gold crown, alongside a dreamy pastel crimson mushroom plushie. Handcrafted with premium hyper-allergenic velvet plush yarn for maximum squishiness.', story: 'These little creatures are born from whimsical childhood fairy tales. Hand-stitched with ultra-soft chenille yarn, each plushie has safety-backed eyes and custom cheek blushes. They make a perfect comfort gift or an aesthetic desktop protector.', materials: ['Super Soft Chenille/Velvet Yarn', 'Hypo-allergenic Polyester Fiberfill', 'Safety Screw Eyes'], careInstructions: ['Spot clean with a damp warm cloth and gentle soap.', 'If fully washed, place in a delicate laundry bag and wash on gentle cycle.', 'Air dry flat; do not tumble dry.'], stockStatus: 'In Stock', isBestSeller: true, isFeatured: true, reviews: makeReviews('Matcha Froggy & Mushroom Duo', 'plushies', 5.0), size: 'Frog: 4.5" tall, Mushroom: 5" tall', colorVariants: [{ name: 'Original Pastels', hex: '#A9C1A5' }, { name: 'Lilac Magic', hex: '#D6C0D8' }] },
  'p-3': { id: 'p-3', name: 'Eternal Cottage Core Bouquet', tagline: 'Lavender and tulips that will bloom forever in your heart.', price: 1250, rating: 4.8, category: 'flowers', image: 'assets/images/crochet_flowers_1783006487670.jpg', secondaryImages: ['assets/images/crochet_flowers_1783006487670.jpg', 'assets/images/crochet_home_decor_1783006530187.jpg'], description: 'A beautifully composed everlasting flower bouquet consisting of hand-knitted lavender stems, soft pink tulips, and golden yellow daisies. Elegantly wrapped in premium organic craft paper and tied with a rustic jute string.', story: 'Fresh cut flowers last a week, but these hand-knitted blossoms carry love forever. Each petal is structured with an internal flexible, rust-proof wire frame, allowing you to gently bend and arrange the stems to fit any vase or posture.', materials: ['Premium Milk Cotton Yarn', 'Flexible Internal Craft Wire', 'Recycled Kraft Wrapping Paper'], careInstructions: ['Gently dust with a soft hair dryer (cool setting) or makeup brush.', 'Avoid high humidity and direct water contact to protect the internal wire.', 'Reshape petals and stems with clean hands whenever needed.'], stockStatus: 'In Stock', isBestSeller: false, isFeatured: true, reviews: makeReviews('Eternal Bouquet', 'flowers', 4.8), size: '14" stem length, 8" bouquet diameter', colorVariants: [{ name: 'Dreamy Lavender & Tulips', hex: '#DFA8B4' }, { name: 'Bright Buttercup & Daisies', hex: '#F4E9E1' }] },
  'p-4': { id: 'p-4', name: 'Warm Mocha Knitted Coaster Set', tagline: 'Protect your morning cups with cozy, chocolate-beige threads.', price: 550, rating: 4.9, category: 'coasters', image: 'assets/images/crochet_coasters_1783006500338.jpg', secondaryImages: ['assets/images/crochet_coasters_1783006500338.jpg', 'assets/images/crochet_bags_hero_1783006461148.jpg'], description: 'A premium set of 4 round, dual-tone crochet coasters handcrafted in deep chocolate brown and soft coffee beige. Thickly woven to absorb moisture and protect delicate tabletops from hot espresso mugs.', story: 'Morning tea and coffee rituals are sacred. These coasters are crafted using an ancient spiral stitching technique, which creates a highly texturized, durable weave that is both beautiful to look at and comforting to touch during your calm morning reading hours.', materials: ['100% Thick Organic Cotton Cord', 'Eco-friendly Natural Vegetable Dyes'], careInstructions: ['Machine washable on cold, gentle cycle with similar colors.', 'Reshape while damp and lay flat to dry completely.'], stockStatus: 'In Stock', isBestSeller: true, isFeatured: false, reviews: makeReviews('Mocha Coaster Set', 'coasters', 4.9), size: '4.5" diameter, 0.25" thick', colorVariants: [{ name: 'Chocolate & Beige', hex: '#70411B' }, { name: 'Sage & Olive', hex: '#A9C1A5' }, { name: 'Rose Petal Duo', hex: '#DFA8B4' }] },
  'p-5': { id: 'p-5', name: 'Fluffy Cherry Hair Bows & Accessories Kit', tagline: 'Add a touch of sweet, Pinterest-approved charm to your hair.', price: 450, rating: 4.7, category: 'accessories', image: 'assets/images/crochet_accessories_1783006515912.jpg', secondaryImages: ['assets/images/crochet_accessories_1783006515912.jpg', 'assets/images/crochet_bags_hero_1783006461148.jpg'], description: 'An adorable set of hair accessories including two hand-stitched pastel pink hair bow clips and matching knitted floral headbands, adorned with delicate cherry dangles. Backed with premium anti-snag metal alligator clips.', story: 'Inspired by retro cottagecore spring vibes, these bows are light as a feather. Handcrafted in a smoke-free, botanical-infused studio using fine merino wool yarns to provide a soft, non-abrasive touch.', materials: ['Fine Merino Wool Blend', 'Anti-snag Stainless Steel Clips', 'Vegan Leather backing'], careInstructions: ['Spot clean bow fibers only.', 'Do not submerge the metal clips in water for long periods.'], stockStatus: 'In Stock', isBestSeller: false, isFeatured: false, reviews: makeReviews('Cherry Hair Bow Kit', 'accessories', 4.7), size: 'Bow width: 3.5", Clip length: 2"', colorVariants: [{ name: 'Blush Cherry', hex: '#DFA8B4' }, { name: 'Warm Apricot', hex: '#F4E9E1' }, { name: 'Sweet Mint', hex: '#A9C1A5' }] },
  'p-6': { id: 'p-6', name: 'Kashmir Mandala Wall Hanging', tagline: 'Intricate knit pattern framed for visual peace.', price: 1450, rating: 4.9, category: 'homedecor', image: 'assets/images/crochet_home_decor_1783006530187.jpg', secondaryImages: ['assets/images/crochet_home_decor_1783006530187.jpg', 'assets/images/crochet_flowers_1783006487670.jpg'], description: 'An elegant wall hanging merging traditional Indian artistry and slow Himalayan aesthetics. Features a complex, mandala-inspired crochet pattern mounted on an organic natural bamboo ring with trailing knitted tassels and soft wooden beads.', story: 'Designed to bring geometric harmony and raw texture into modern homes. Over 2,500 individual knit locks come together to form this gorgeous medallion, echoing ancient lace patterns updated with contemporary, warm earth colors.', materials: ['Premium Natural Unbleached Cotton Rope', 'Organic Bamboo Hoop', 'Sustainably Sourced Wooden Beads'], careInstructions: ['Gently shake outdoor to remove dust.', 'Use a wide-tooth comb to gently brush the bottom tassels if they get tangled.'], stockStatus: 'Low Stock', isBestSeller: false, isFeatured: true, reviews: makeReviews('Mandala Wall Hanging', 'homedecor', 4.9), size: '10" hoop diameter, 24" total length from hanging cord', colorVariants: [{ name: 'Sand & Oatmeal', hex: '#F4E9E1' }, { name: 'Earthy Charcoal', hex: '#70411B' }] },
  'p-7': { id: 'p-7', name: 'Autumn Bloom Cotton Crochet Cardigan', tagline: 'Wrap yourself in soft, breathable floral motifs.', price: 2999, rating: 5.0, category: 'wearables', image: 'assets/images/crochet_wearables_1783006542606.jpg', secondaryImages: ['assets/images/crochet_wearables_1783006542606.jpg', 'assets/images/crochet_bags_hero_1783006461148.jpg'], description: 'An absolute masterpiece of wearable art. This oversized beige crochet shrug cardigan is hand-stitched out of ultra-breathable milk cotton. Adorned with beautiful raised floral motifs in soft pastel pink, sage, and chocolate tones.', story: 'Creating a single Autumn Bloom Cardigan requires exactly 28 individual floral granny squares, sewn together by hand over 3 days of rigorous artisanal labor. It drapes gracefully, feels cozy like a warm hug, and stands out in any crowd.', materials: ['60% Premium Milk Cotton', '40% Soft Acrylic Blend'], careInstructions: ['Always hand wash in cold water or dry clean.', 'Never hang dry; always lay flat on a drying rack to prevent stretching and distortion of stitches.'], stockStatus: 'Pre-Order', isBestSeller: true, isFeatured: true, reviews: makeReviews('Autumn Bloom Cardigan', 'wearables', 5.0), size: 'One-size fits most (Oversized design, Chest width 22", Length 24")', colorVariants: [{ name: 'Vintage Beige', hex: '#F4E9E1' }, { name: 'Cozy Cinnamon', hex: '#9A5B2A' }] },
  'p-8': { id: 'p-8', name: 'Strawberry Bubble Tea Keychain', tagline: 'A tiny, lovable boba companion for your keys or backpack.', price: 350, rating: 4.8, category: 'keychains', image: 'assets/images/crochet_accessories_1783006515912.jpg', secondaryImages: ['assets/images/crochet_accessories_1783006515912.jpg', 'assets/images/crochet_plushies_1783006474452.jpg'], description: 'A miniature crochet keychain shaped like a delicious strawberry bubble tea. Complete with tiny hand-stitched black boba pearls, a cute felt straw, and a stainless steel clasp. Fits keys, handbags, and backpacks.', story: 'Hand-knitted with extra tight stitching to prevent wear-and-tear, this micro boba cup plushie keychain is a fan favorite for school backpacks and couples looking for matching sweet charms.', materials: ['Tight Weave Combed Cotton', 'Stainless Gold Keyring', 'Felt details'], careInstructions: ['Damp spot cleaning recommended.', 'Do not machine wash.'], stockStatus: 'In Stock', isBestSeller: true, isFeatured: false, reviews: makeReviews('Strawberry Boba Keychain', 'keychains', 4.8), size: '2.5" tall, 1.5" wide', colorVariants: [{ name: 'Strawberry Pink', hex: '#DFA8B4' }, { name: 'Matcha Green', hex: '#A9C1A5' }] },
  'p-9': { id: 'p-9', name: 'Nazar Battu — Crochet Evil Eye Protector', tagline: 'Hang this hand-loomed protection charm on your bag, car mirror, or doorway.', price: 499, rating: 4.9, category: 'accessories', image: 'assets/images/crochet_accessories_1783006515912.jpg', secondaryImages: ['assets/images/crochet_accessories_1783006515912.jpg', 'assets/images/crochet_home_decor_1783006530187.jpg'], description: 'An elegant, high-contrast crochet interpretation of the traditional Indian Nazar Battu (Evil Eye protector charm). Meticulously row-stitched with vibrant indigo, sky blue, and pure white organic cotton thread, finished with a beautiful fluffy tassel.', story: 'Inspired by traditional Indian folklore, our master knitters created this Nazar amulet as a modern, soft protection charm. It is said to ward off negative vibes while adding a beautiful, aesthetic touch to your space or bag styling.', materials: ['100% Organic Cotton Thread', 'Hypoallergenic Stuffing', 'Handmade Indigo Cotton Tassel'], careInstructions: ['Gentle spot cleaning with a soft damp cloth recommended.', 'Do not bleach or dry clean.', 'Reshape the tassel threads with a small comb if they become tangled.'], stockStatus: 'In Stock', isBestSeller: true, isFeatured: true, reviews: makeReviews('Nazar Battu Protector', 'accessories', 4.9), size: '3.5" amulet diameter, 9" total length with tassel', colorVariants: [{ name: 'Indigo Classic', hex: '#3B82F6' }, { name: 'Teal Meadow', hex: '#0D9488' }] },
  'p-10': { id: 'p-10', name: 'Genda Phool — Eternal Marigold Flower Stem', tagline: 'Bright saffron and yellow crochet blossoms that celebrate festive warmth.', price: 299, rating: 5.0, category: 'flowers', image: 'assets/images/crochet_flowers_1783006487670.jpg', secondaryImages: ['assets/images/crochet_flowers_1783006487670.jpg', 'assets/images/crochet_home_decor_1783006530187.jpg'], description: 'A gorgeously textured hand-knitted Marigold (Genda) stem, perfect for your study table, home mandir, festive corners, or permanent floral arrangements. The high-density loop stitches beautifully replicate the dense, circular petals of real marigold flowers.', story: 'A festive homage to the iconic Indian Genda Phool. Handcrafted with premium, non-fading double-mercerized yarn, this stem provides a sustainable, eco-friendly, and everlasting alternative to fresh floral garlands for a cozy lifestyle.', materials: ['Premium Mustard and Saffron Milk Cotton Yarn', 'Flexible internal bendable wire'], careInstructions: ['Damp clean with a soft microfiber cloth or blow off dust with a hairdryer.', 'Keep away from water and damp areas to prevent the internal stem wire from oxidation.'], stockStatus: 'In Stock', isBestSeller: false, isFeatured: true, reviews: makeReviews('Genda Phool Stem', 'flowers', 5.0), size: '12" stem length, 3" blossom diameter', colorVariants: [{ name: 'Saffron Orange', hex: '#EA580C' }, { name: 'Bright Mustard Yellow', hex: '#EAB308' }] },
  'p-11': { id: 'p-11', name: 'Phool Kari — Artisan Floral Crochet Belt', tagline: 'A beautiful hand-knitted waist belt featuring raised flower motifs.', price: 799, rating: 4.8, category: 'accessories', image: 'assets/images/crochet_bags_hero_1783006461148.jpg', secondaryImages: ['assets/images/crochet_bags_hero_1783006461148.jpg', 'assets/images/crochet_accessories_1783006515912.jpg'], description: 'An elegant, waist-cinching belt hand-woven with high-strength organic cotton cords and adorned with beautiful raised floral patterns. Ties gracefully around the waist with soft, hand-braided wool tassels.', story: 'Designed to bridge retro bohemian styling with traditional Indian Phulkari florals. It styles elegantly over a plain white kurta, a flowing maxi dress, or standard denim to add a warm, handwoven touch.', materials: ['Organic Unbleached Cotton Cord', 'Fine Merino Wool Flower Accents'], careInstructions: ['Dry clean recommended to preserve the shape of the raised wool flowers.', 'Or hand wash cold gently; lay flat to dry.'], stockStatus: 'In Stock', isBestSeller: false, isFeatured: false, reviews: makeReviews('Phool Kari Belt', 'accessories', 4.8), size: '2.5" belt width, 40" main body length, 15" braid ties at each end', colorVariants: [{ name: 'Ivory Meadow', hex: '#FFFBF7' }, { name: 'Cinnamon Dust', hex: '#9A5B2A' }] },
  'p-12': { id: 'p-12', name: 'Shimla Slouchy Crochet Beanie', tagline: 'Stay beautifully cozy in this hand-ribbed waffle knit beanie.', price: 699, rating: 4.9, category: 'wearables', image: 'assets/images/crochet_wearables_1783006542606.jpg', secondaryImages: ['assets/images/crochet_wearables_1783006542606.jpg', 'assets/images/crochet_accessories_1783006515912.jpg'], description: 'An ultra-cozy slouchy beanie featuring a rich, textured waffle stitch that holds heat perfectly while feeling incredibly light and soft on your forehead. Features a snug, stretchy ribbed edge.', story: 'Knitted in warm tribute to chilly Himalayan mornings in Shimla. Hand-loomed with extremely soft, premium milk cotton fibers to ensure a non-itchy, highly breathable wear for everyday adventures.', materials: ['80% Premium Soft Milk Cotton Yarn', '20% Wool blend'], careInstructions: ['Hand wash cold only with gentle wool soap.', 'Never tumble dry; squeeze excess water in a towel and air dry flat.'], stockStatus: 'In Stock', isBestSeller: true, isFeatured: true, reviews: makeReviews('Shimla Beanie', 'wearables', 4.9), size: 'One size fits most (Highly stretchy design, 9" x 10")', colorVariants: [{ name: 'Vintage Oats', hex: '#F4E9E1' }, { name: 'Sage Green', hex: '#A9C1A5' }, { name: 'Deep Crimson', hex: '#70411B' }] },
  'p-13': { id: 'p-13', name: 'Jhumka Loops — Mini Crochet Floral Earrings', tagline: 'Featherlight hand-knitted floral drops with delicate seed beads.', price: 249, rating: 4.7, category: 'accessories', image: 'assets/images/crochet_accessories_1783006515912.jpg', secondaryImages: ['assets/images/crochet_accessories_1783006515912.jpg', 'assets/images/crochet_bags_hero_1783006461148.jpg'], description: 'Charming micro-crochet earrings resembling miniature Indian jhumkas, adorned with soft cotton loops, a single hanging glass bead, and gold-plated hypoallergenic hooks.', story: 'Crafted for lovers of quirky, lightweight traditional Indian accents. These earrings are crocheted using single-ply thread under magnifying lenses in our cottage studio, weighing less than a small coin.', materials: ['Micro-ply Mercerized Cotton Thread', 'Gold-plated Hypoallergenic Hooks', 'Tiny Glass Seed Beads'], careInstructions: ['Spot clean the crochet fibers gently with a dry cloth.', 'Keep away from water, perfumes, and spray cosmetics to protect the metal hooks.'], stockStatus: 'In Stock', isBestSeller: false, isFeatured: false, reviews: makeReviews('Jhumka Loops', 'accessories', 4.7), size: '2.5" drop length, 1" bell width', colorVariants: [{ name: 'Marigold & Gold', hex: '#EAB308' }, { name: 'Peach Rose', hex: '#DFA8B4' }, { name: 'Teal Sparkle', hex: '#0D9488' }] },
  'p-14': { id: 'p-14', name: 'Gulmarg Cable-Knit Crochet Muffler', tagline: 'A luxurious, extra-long winter scarf with classic cable details.', price: 1199, rating: 5.0, category: 'wearables', image: 'assets/images/crochet_wearables_1783006542606.jpg', secondaryImages: ['assets/images/crochet_wearables_1783006542606.jpg', 'assets/images/crochet_flowers_1783006487670.jpg'], description: 'A handsome, dense cable-knit scarf styled with generous fluffy fringe details at both ends. Designed to wrap comfortably twice around your neck for maximum winter insulation.', story: 'Reminiscent of snowy forest walks in Gulmarg. Stitched with super-thick premium luxury wool-acrylic fibers that hold their shape beautifully and resist pilling over years of crisp winters.', materials: ['50% Australian Merino Wool', '50% Anti-pilling Premium Acrylic'], careInstructions: ['Gentle hand wash in cold water with wool conditioner.', 'Lay flat to dry; do not iron or bleach.'], stockStatus: 'Pre-Order', isBestSeller: true, isFeatured: false, reviews: makeReviews('Gulmarg Scarf', 'wearables', 5.0), size: '72" length excluding fringe, 8" width', colorVariants: [{ name: 'Snow Cream', hex: '#FFFBF7' }, { name: 'Mustard Saffron', hex: '#EAB308' }, { name: 'Earthy Charcoal', hex: '#70411B' }] },
  'p-15': { id: 'p-15', name: 'Mitti Pot — Mini Crochet Succulent & Flower Pot', tagline: 'An adorable, everlasting mini desk plant in a knitted clay pot.', price: 599, rating: 4.9, category: 'homedecor', image: 'assets/images/crochet_home_decor_1783006530187.jpg', secondaryImages: ['assets/images/crochet_home_decor_1783006530187.jpg', 'assets/images/crochet_flowers_1783006487670.jpg'], description: 'An incredibly charming, zero-maintenance desk companion featuring a hand-knitted miniature succulent plant nestled inside a stitched mitti (clay) colored pot.', story: 'Perfect for dark bookshelves, study tables, or cozy office desks where live plants struggle. Every succulent leaf is hand-sculpted with soft wool stuffing.', materials: ['Hypoallergenic Cotton Yarn', 'Solid Cardboard Bottom Insert', 'Safety Fiberfill'], careInstructions: ['Gently dust with a soft brush.', 'Do not wash as it contains a solid internal base.'], stockStatus: 'In Stock', isBestSeller: false, isFeatured: true, reviews: makeReviews('Mitti Pot', 'homedecor', 4.9), size: '5" tall, 3" pot diameter', colorVariants: [{ name: 'Clay Pot & Sage Green', hex: '#A9C1A5' }] },
  'p-16': { id: 'p-16', name: 'Darjeeling Fingerless Crochet Gloves', tagline: 'Keep your hands warm while typing, writing, or holding a cup of hot chai.', price: 499, rating: 4.8, category: 'wearables', image: 'assets/images/crochet_accessories_1783006515912.jpg', secondaryImages: ['assets/images/crochet_accessories_1783006515912.jpg', 'assets/images/crochet_wearables_1783006542606.jpg'], description: 'Elegant fingerless gloves featuring ribbed wrist cuffs and beautiful decorative stitching across the knuckles. Allows full use of touchscreens and phones.', story: 'Inspired by misty mornings in Darjeeling tea gardens. Hand-woven with a flexible ribbed stitch that conforms comfortably to any hand size.', materials: ['100% Breathable Soft Milk Cotton Yarn'], careInstructions: ['Hand wash gently in cold water.', 'Reshape and dry flat in shade.'], stockStatus: 'In Stock', isBestSeller: false, isFeatured: false, reviews: makeReviews('Darjeeling Gloves', 'wearables', 4.8), size: 'One size fits most (Stretchy length 7.5", Width 3.5")', colorVariants: [{ name: 'Teal Mist', hex: '#0D9488' }, { name: 'Soft Peach', hex: '#DFA8B4' }] },
  'p-17': { id: 'p-17', name: 'MangoPaglu Checkerboard Wall Hanging 🥭', tagline: 'Vibrant pink-checkerboard wall piece with a delightful yellow mango centerpiece.', price: 650, rating: 4.9, category: 'homedecor', image: 'assets/images/crochet_home_decor_1783006530187.jpg', secondaryImages: ['assets/images/crochet_home_decor_1783006530187.jpg', 'assets/images/crochet_accessories_1783006515912.jpg'], description: 'Add a punchy, warm summer vibe to your bedroom with MangoPaglu! This stunning hand-woven checkerboard hanging showcases a bright yellow mango, knitted stitch-by-stitch with robust, premium-grade Indian cotton yarn. It is the ultimate accent for any cozy corner.', story: 'Born from a craving for ripe summer mangoes during a rainy afternoon in the scenic foothills of Haldwani. Our design pairs a retro checkered backdrop with organic fruit shapes to form a unique, eye-catching tapestry.', materials: ['100% Premium Combed Cotton Thread', 'Sturdy Natural Pine Wooden Dowel'], careInstructions: ['Gently dust with a clean, dry microfiber cloth.', 'Do not wash or submerge in water.'], stockStatus: 'In Stock', isBestSeller: true, isFeatured: true, reviews: makeReviews('MangoPaglu Wall Hanging', 'homedecor', 4.9), size: '10" width x 16" length', colorVariants: [{ name: 'Strawberry & Mango', hex: '#EAAFB9' }] },
  'p-18': { id: 'p-18', name: 'Cozy Nazar Battu Evil Eye Coasters 🧿', tagline: 'Keep negative vibes away from your table with these beautiful round protectors.', price: 499, rating: 5.0, category: 'coasters', image: 'assets/images/crochet_coasters_1783006500338.jpg', secondaryImages: ['assets/images/crochet_coasters_1783006500338.jpg', 'assets/images/crochet_accessories_1783006515912.jpg'], description: 'A premium set of 4 round, multi-layered crochet coasters styled as the protective Nazar eye. Thickly loop-woven to easily absorb condensation from cold iced teas or shield wood from boiling-hot copper chai cups.', story: 'Inspired by the traditional Indian Nazar Battu. We reimagined this cultural protective motif as soft, beautiful household items that bring positive energy and handwoven comfort to your daily table setup.', materials: ['High-Strength Eco Cotton Twine', 'Organic Indigo Vegetable Dyes'], careInstructions: ['Gently wash by hand in cold water.', 'Lay completely flat to dry in shade to keep the round shape.'], stockStatus: 'In Stock', isBestSeller: true, isFeatured: true, reviews: makeReviews('Evil Eye Coasters', 'coasters', 5.0), size: '4.5" diameter, 0.2" thickness', colorVariants: [{ name: 'Indigo & Sky Blue', hex: '#1E40AF' }] },
  'p-19': { id: 'p-19', name: 'Lilac Crochet Bralette Halter Top 🌸', tagline: 'An incredibly soft, custom-fit bralette in dreamy pastel tones.', price: 1199, rating: 4.8, category: 'wearables', image: 'assets/images/crochet_wearables_1783006542606.jpg', secondaryImages: ['assets/images/crochet_wearables_1783006542606.jpg', 'assets/images/crochet_accessories_1783006515912.jpg'], description: 'An absolutely stunning halter-neck bralette knit in soft pastel lavender and baby pink. Double-stitched for perfect opacity, and featuring adjustable corset-style back ties to provide a highly custom, breathable fit.', story: 'Designed for summer styling, music festivals, or layering under airy linen shirts. Each bralette takes our knitters approximately 8 hours of close, tight stitching to ensure comfortable, supportive elasticity.', materials: ['Premium Breathable Milk Cotton Yarn', 'Elastic Core Thread'], careInstructions: ['Gently hand wash in cold water using a mild delicate wash.', 'Squeeze out excess water in a towel; lay flat to dry in shade.'], stockStatus: 'Pre-Order', isBestSeller: false, isFeatured: true, reviews: makeReviews('Lilac Bralette Top', 'wearables', 4.8), size: 'Available in Custom Sizes (S, M, L, XL - adjust via ties)', colorVariants: [{ name: 'Lavender & Blush Pink', hex: '#D6C0D8' }] },
  'p-20': { id: 'p-20', name: 'Sunflower & Cherry Joy Hairtie Duo 🌻', tagline: 'Double your cuteness with a twin sunflower and leaf ponytail holder.', price: 299, rating: 4.9, category: 'accessories', image: 'assets/images/crochet_accessories_1783006515912.jpg', secondaryImages: ['assets/images/crochet_accessories_1783006515912.jpg', 'assets/images/crochet_plushies_1783006474452.jpg'], description: 'Bring bright, cheerful sunflower energy to your hair styling! This lovely hair tie features two micro-crocheted sunflower blooms paired with dainty green leaves on a high-elastic, anti-snag hairband. Stays snug all day.', story: 'Crafted as a playful, Pinterest-aesthetic hair accessory that matches sunny days and outdoor picnics. The sunflowers are crocheted with double-twisted thread so they never lose their perky shape.', materials: ['Double-twisted Fine Cotton Thread', 'Extra-Strength Elastic Ponytail Ring'], careInstructions: ['Spot clean with cold water only.', 'Do not machine wash or scrub the petals.'], stockStatus: 'In Stock', isBestSeller: true, isFeatured: false, reviews: makeReviews('Sunflower Hairtie', 'accessories', 4.9), size: 'Sunflower Diameter: 1.8" each', colorVariants: [{ name: 'Golden Sun & Forest Green', hex: '#EAB308' }] },
  'p-21': { id: 'p-21', name: 'Blooming Rose AirPods Crochet Pouch 🌹', tagline: 'A lovely rose-pink sleeve that protects your AirPods in style.', price: 399, rating: 4.8, category: 'accessories', image: 'assets/images/crochet_accessories_1783006515912.jpg', secondaryImages: ['assets/images/crochet_accessories_1783006515912.jpg', 'assets/images/crochet_bags_hero_1783006461148.jpg'], description: 'A charming, high-protection pouch shaped like a blooming rose in dusty pink. Includes a snug-fit design to protect your AirPods case from drops and scratches, and a leaf-shaped loop to attach to keys or backpacks.', story: 'We wanted to turn standard tech accessories into warm, natural art. This rose pouch features a soft, thick cushion of cotton loops that absorb impacts, with a handy slit at the bottom for easy charging access.', materials: ['Premium Double-Strand Milk Cotton Yarn', 'Brass Keyring Clasp'], careInstructions: ['Hand wash cold gently; air dry completely.', 'Remove AirPods case before washing.'], stockStatus: 'In Stock', isBestSeller: false, isFeatured: false, reviews: makeReviews('Rose AirPods Pouch', 'accessories', 4.8), size: 'Compatible with AirPods Gen 1/2/3 and Pro models', colorVariants: [{ name: 'Rose Pink & Emerald Leaf', hex: '#DFA8B4' }] },
  'p-22': { id: 'p-22', name: 'Daisy-Accent Woolen Baby Booties 👶', tagline: 'Ultra-soft, organic milk cotton shoes to keep tiny feet cozy.', price: 599, rating: 5.0, category: 'accessories', image: 'assets/images/crochet_accessories_1783006515912.jpg', secondaryImages: ['assets/images/crochet_accessories_1783006515912.jpg', 'assets/images/crochet_home_decor_1783006530187.jpg'], description: 'The sweetest little shoes for your baby! Hand-knitted with buttery-soft, hypoallergenic organic milk cotton yarn that is entirely itch-free and warm. Detailed with tiny daisy flowers stitched on the toes and a delicate ankle tie.', story: 'A perfect newborn gift, crafted with extra loose breathing loops to keep tiny feet cozy without restricting blood flow. Designed and sized with care at 4.5 inches to snugly fit infants from 0 to 6 months.', materials: ['100% Super-Soft Milk Cotton Yarn', 'Anti-fray Ankle Ties'], careInstructions: ['Hand wash gently in cool water with baby-safe liquid wash.', 'Lay flat on dry towel to preserve the cute bootie shape.'], stockStatus: 'In Stock', isBestSeller: true, isFeatured: true, reviews: makeReviews('Daisy Baby Booties', 'accessories', 5.0), size: '4.5" sole length (Best fits 0 - 6 months)', colorVariants: [{ name: 'Cream & Buttercup Daisy', hex: '#FFFBF7' }] }
}

/* ── Export to window for other modules ──────────────────────────────── */

window.$ = $
window.$$ = $$
window.on = on
window.delegate = delegate
window.store = store
window.debounce = debounce
window.throttle = throttle
window.createSpring = createSpring
window.formatPrice = formatPrice
window.clamp = clamp
window.products = products
window.COUPONS = COUPONS
window.galleryItems = galleryItems
window.faqs = faqs
